using Microsoft.Agents.AI;
using TaskForge.AiAgent.Llm;
using TaskForge.AiAgent.Prompts;
using TaskForge.AiAgent.Runtime;

namespace TaskForge.AiAgent.Workflows.Executors;

public sealed class PlanRequestExecutor
{
    private readonly TaskForgeAgentFactory _agentFactory;
    private readonly AgentSessionStore _sessionStore;
    private readonly AgentStepReporter _steps;
    private AIAgent? _agent;

    public PlanRequestExecutor(TaskForgeAgentFactory agentFactory, AgentSessionStore sessionStore, AgentStepReporter steps)
    {
        _agentFactory = agentFactory;
        _sessionStore = sessionStore;
        _steps = steps;
    }

    public async Task<string> ExecuteAsync(WorkflowState state, string contextPrompt, CancellationToken cancellationToken)
    {
        _agent ??= _agentFactory.CreateCoordinatorAgent();
        await _steps.TryReportAsync("planning", "running", "Планирую действия агента", "Агент выберет tools/workflow strategy, а не один жёсткий Python-сценарий.");

        var session = await _sessionStore.LoadAsync(_agent, state.Job.ConversationId, cancellationToken);
        var prompt = $$"""
{{TaskForgeAgentPrompts.Coordinator}}

Нужно составить короткий план действий для workflow '{{state.WorkflowName}}'.
Не выполняй write-действия. Если нужны изменения, планируй approval/artifact.

{{contextPrompt}}

Верни краткий план на русском и перечисли, какие tools нужны.
""";
        var response = await _agent.RunAsync(prompt, session, cancellationToken: cancellationToken);
        await _sessionStore.SaveAsync(_agent, session, state.Job.ConversationId, cancellationToken);
        var text = response.Text ?? "План не был сформирован моделью.";
        state.Data["plan"] = text;
        state.Notes.Add("Plan generated by coordinator agent.");
        await _steps.TryReportAsync("planning", "completed", "План готов", text.Length > 700 ? text[..700] : text);
        return text;
    }
}
