namespace taskforge.Services.AI;

internal static class AiGenerationScenarioCatalog
{
    public static readonly IReadOnlyList<AiGenerationScenarioDefinition> Definitions = new List<AiGenerationScenarioDefinition>
    {
        D("guided-onboarding-ladder", "Обучающая лесенка", "progression", "guided-onboarding-ladder", true, true, true, false, false, true, 5,
            ["обучалк", "обучающ", "лесенк", "научить пользоваться", "научить работать", "перед if", "до if", "до первого if", "перед темой", "перед новой темой", "мягко подвести", "подвести к теме", "friendly walkthrough", "guided onboarding", "guided intro"],
            ["одну сложную", "без разжёвывания", "без обучалки"]),
        D("step-by-step-ladder", "Лесенка", "progression", "guided-sequence", true, true, true, false, false, false, 5,
            ["лесенк", "пошаг", "шаг за шаг", "с нуля", "первые шаги", "маленьких программ", "серия маленьких"],
            ["одну сложную", "без разжёвывания"]),
        D("new-topic-intro", "Новая тема", "topic", "topic-pack", true, false, false, false, false, true, 3,
            ["новая тема", "ввести тему", "начать тему", "вход в тему", "first topic", "introduce topic"],
            ["расширение", "углубить"]),
        D("topic-expansion", "Расширение старой темы", "topic", "topic-pack", false, false, false, false, false, false, 3,
            ["расширение", "углубить", "продолжить тему", "расширить тему", "докрутить тему"],
            ["новая тема"]),
        D("course-gap-audit", "Проверка курса на дырки", "audit", "topic-pack", false, false, false, false, false, true, 3,
            ["дырки", "пробелы", "проверь курс", "аудит курса", "что пропущено", "gap audit"],
            ["сгенерируй сразу"]),
        D("reorder-auto", "Перестановка как нейронка", "reordering", "topic-pack", false, false, false, false, false, true, 1,
            ["перестановка", "переупорядоч", "как нейронка", "как ai", "авто порядок"],
            ["как человек скажет"]),
        D("reorder-manual", "Перестановка как скажет человек", "reordering", "topic-pack", false, false, false, false, false, false, 1,
            ["как человек скажет", "строго по моему порядку", "по моей команде переставь", "manual reorder"],
            ["как нейронка"]),
        D("split-heavy-topic", "Разрезать сложную тему", "structure", "topic-pack", true, true, false, false, false, false, 3,
            ["разбить тему", "слишком сложно", "разрезать", "дробить", "split topic"],
            ["объединить"]),
        D("compress-stretched-topic", "Сжать растянутую тему", "structure", "topic-pack", false, false, false, false, false, false, 1,
            ["сжать", "объединить задачи", "слишком растянуто", "compress topic"],
            ["разбить", "дробить"]),
        D("pretopic-bridges", "Подводка к теме", "transition", "bridge-pack", true, true, false, false, false, true, 5,
            ["мостик", "bridge", "подводящ", "перед темой", "до темы", "подвести к теме"],
            ["после темы"]),
        D("posttopic-reinforcement", "Закрепление после темы", "transition", "topic-pack", true, false, false, false, false, false, 4,
            ["после темы", "закрепление", "после блока", "reinforcement", "закрепить"],
            ["до темы"]),
        D("spaced-repetition", "Повторение темы позже", "progression", "topic-pack", false, false, false, false, false, false, 3,
            ["повторить позже", "вернуть тему", "спустя несколько уроков", "spaced repetition"],
            []),
        D("topic-transition", "Переход между темами", "transition", "bridge-pack", true, false, false, false, false, true, 3,
            ["переход между темами", "стык тем", "между темами", "transition between"],
            []),
        D("restore-sequence", "Восстановление последовательности", "structure", "topic-pack", false, false, false, false, false, true, 3,
            ["сломанная последовательность", "восстановить порядок", "broken sequence", "исправить последовательность"],
            []),
        D("fill-course-gap", "Заполнение пустого участка", "structure", "bridge-pack", true, false, false, false, false, true, 3,
            ["заполнить пустой участок", "между заданиями", "скачок", "fill gap"],
            []),
        D("single-deep-task", "Одна сложная задача", "difficulty", "single-draft", false, false, false, false, true, false, 1,
            ["одну сложную", "одну сильную", "без разжёвывания", "посложнее", "deep task", "challenge"],
            ["лесенк", "несколько маленьких"]),
        D("advanced-pack", "Пакет сложных задач", "difficulty", "topic-pack", false, false, false, false, false, false, 3,
            ["пакет сложных", "несколько сложных", "advanced pack", "сложные задачи"],
            ["пошаг", "с нуля"]),
        D("difficulty-smoothing", "Выравнивание сложности", "difficulty", "topic-pack", false, false, false, false, false, true, 3,
            ["выравнивание сложности", "скачок сложности", "сделай плавнее", "difficulty smoothing"],
            []),
        D("difficulty-raise", "Повышение сложности", "difficulty", "topic-pack", false, false, false, false, false, false, 3,
            ["поднять сложность", "усложнить", "harder", "сделай взрослее"],
            ["упрости"]),
        D("difficulty-lower", "Упрощение блока", "difficulty", "topic-pack", true, true, false, false, false, false, 3,
            ["упрости", "понизить сложность", "слишком сложно для новичка", "make easier"],
            ["усложнить"]),
        D("milestone-checkpoint", "Контрольная точка", "assessment", "topic-pack", false, false, false, false, false, false, 1,
            ["контрольная", "milestone", "проверочная", "checkpoint", "контрольная точка"],
            []),
        D("micro-program-series", "Серия маленьких программ", "pedagogy", "guided-sequence", true, true, true, false, false, false, 5,
            ["несколько программ", "маленькие программы", "мини программы", "series of programs", "практических мини"],
            ["одну сложную"]),
        D("story-driven-task", "Сюжетная задача", "pedagogy", "single-draft", false, false, false, false, false, false, 1,
            ["сюжетную", "история", "story task", "сценарную задачу"],
            []),
        D("comparison-learning", "Обучение через сравнение", "pedagogy", "topic-pack", false, false, false, false, false, false, 2,
            ["через сравнение", "сравнить подходы", "compare approaches", "сопоставь"],
            []),
        D("common-mistakes", "Обучение через ошибки", "pedagogy", "topic-pack", false, false, false, false, false, false, 3,
            ["типичные ошибки", "частые ошибки", "ловить ошибки", "common mistakes"],
            []),
        D("remediation-pack", "Добивание слабых мест", "pedagogy", "topic-pack", true, false, false, false, false, true, 4,
            ["добить слабые места", "remediation", "исправить слабые места", "закрыть пробелы"],
            []),
        D("restyle-explanation", "Переобъяснение темы", "pedagogy", "single-draft", true, false, false, false, false, false, 1,
            ["объясни иначе", "другим стилем", "переобъясни", "restyle"],
            []),
        D("theory-to-practice", "Превратить теорию в задачи", "format", "topic-pack", true, false, false, false, false, false, 3,
            ["из теории в задачи", "преврати теорию", "theory to practice"],
            []),
        D("practice-to-theory", "Превратить задачи в теорию", "format", "single-draft", false, false, false, false, false, false, 1,
            ["из задач в теорию", "practice to theory", "конспект по задачам"],
            []),
        D("programming-quiz", "Тесты по программированию", "tests", "topic-pack", false, false, false, false, false, false, 10,
            ["тесты", "quiz", "варианты ответов", "выбор ответа", "по программированию"],
            ["русскому языку"]),
        D("russian-language-tests", "Тесты по русскому языку", "tests", "topic-pack", false, false, false, false, false, false, 10,
            ["русский язык", "по русскому", "орфография", "пунктуация", "генерация тестов по русскому языку"],
            ["c++", "программированию"]),
        D("general-topic-pack", "Общий пакет задач", "general", "topic-pack", false, false, false, false, false, false, 3,
            ["задач", "упражнен", "practice"],
            [])
    };

    private static AiGenerationScenarioDefinition D(
        string id,
        string displayName,
        string family,
        string defaultBatchMode,
        bool preferGuidedWalkthroughs,
        bool preferTinySteps,
        bool forceSmallPrograms,
        bool requireExplicitIf,
        bool preferSingleDeepTask,
        bool preferCourseAudit,
        int defaultCount,
        IReadOnlyList<string> aliases,
        IReadOnlyList<string> antiSignals)
        => new(id, displayName, family, defaultBatchMode, preferGuidedWalkthroughs, preferTinySteps, forceSmallPrograms, requireExplicitIf, preferSingleDeepTask, preferCourseAudit, defaultCount, aliases, antiSignals);
}
