map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}

map $http_x_forwarded_proto $forwarded_proto {
  default $scheme;
  ~^(http|https)$ $http_x_forwarded_proto;
}

map $forwarded_proto $forwarded_ssl {
  default off;
  https on;
}

map $http_host $forwarded_port {
  default $server_port;
  ~^[^:]+:(?<host_port>[0-9]+)$ $host_port;
}

server {
  listen 80;
  server_name ${DOMAIN};
  client_max_body_size 80m;
  absolute_redirect off;
  server_name_in_redirect off;
  port_in_redirect off;

  include /etc/nginx/snippets/acme.conf;
  include /etc/nginx/snippets/proxy-common.conf;
  include /etc/nginx/snippets/api-routes.conf;
  include /etc/nginx/snippets/hub-routes.conf;

  location / {
    proxy_pass http://front:80;
  }
}

server {
  listen 80;
  server_name ${CT_DOMAIN};
  client_max_body_size 80m;
  absolute_redirect off;
  server_name_in_redirect off;
  port_in_redirect off;

  include /etc/nginx/snippets/acme.conf;
  include /etc/nginx/snippets/proxy-common.conf;
  include /etc/nginx/snippets/api-routes.conf;
  include /etc/nginx/snippets/hub-routes.conf;

  location / {
    proxy_pass http://front-ct:80;
  }
}
