plugins {
    id 'java'
}

group = 'me.vasya'
version = '2.5.0'

def targetJava = 25
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(targetJava)
    }
}

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:26.1.2.build.74-stable'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release.set(targetJava)
}

jar {
    archiveBaseName = 'CustomMobTweaks'
}
