import React, { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, BookOpen, ChevronRight, ClipboardList, FileText, Loader2, PencilLine, PlayCircle, Sparkles } from 'lucide-react';
import Layout from '../components/Layout';
import { getLearningCourseOutline, getLearningCourseTree } from '../api/learning';
import { getQuizTasks } from '../api/quiz';
import { useEditorMode } from '../contexts/EditorModeContext';
function findPath(nodes, slug, path = []) { for (const n of nodes || []) { const next = [...path, n]; if (n.slug === slug) return next; const child = findPath(n.children, slug, next); if (child) return child; } return null; }
function typeLabel(c) { if (c?.sectionCode) return 'Раздел экзамена'; if (c?.examCode) return 'Курс подготовки'; if (!c?.parentCourseId) return 'Предмет'; return 'Учебный раздел'; }
function taskParams(c) { const p = new URLSearchParams(); if (c?.subjectCode) p.set('subjectCode', c.subjectCode); if (c?.examCode) p.set('examCode', c.examCode); if (c?.sectionCode) p.set('sectionCode', c.sectionCode); return p.toString(); }
export default function LearningCoursePage() {
  const { courseSlug } = useParams();
  const { canEdit, isEditorMode } = useEditorMode();
  const [outline, setOutline] = useState(null), [tree, setTree] = useState([]), [quizTasks, setQuizTasks] = useState([]), [loading, setLoading] = useState(true), [error, setError] = useState('');
  useEffect(() => { let off = false; (async () => { try { setLoading(true); const [o, t] = await Promise.all([getLearningCourseOutline(courseSlug, { includeDraft: isEditorMode }), getLearningCourseTree({ includeDraft: isEditorMode })]); if (off) return; setOutline(o); setTree(t || []); const c = o?.course; if (c?.sectionCode) { try { const tasks = await getQuizTasks({ subjectCode: c.subjectCode || undefined, examCode: c.examCode || undefined, sectionCode: c.sectionCode }); if (!off) setQuizTasks(tasks || []); } catch { if (!off) setQuizTasks([]); } } else setQuizTasks([]); } catch (e) { if (!off) setError(e?.userMessage || e?.message || 'Не удалось открыть учебный курс.'); } finally { if (!off) setLoading(false); } })(); return () => { off = true; }; }, [courseSlug, isEditorMode]);
  const c = outline?.course; const path = useMemo(() => findPath(tree, courseSlug) || [], [tree, courseSlug]); const q = taskParams(c); const href = (slug) => isEditorMode ? `/editor/courses/${slug}` : `/courses/${slug}`;
  return <Layout fullWidth><div className="min-h-[calc(100vh-57px)] bg-neutral-50 dark:bg-neutral-950"><div className="container-app py-6 lg:py-8">
    <div className="flex flex-wrap items-center justify-between gap-3"><Link to={isEditorMode ? '/editor' : '/'} className="inline-flex items-center gap-2 text-sm font-semibold text-brand-700 dark:text-brand-300 hover:underline"><ArrowLeft size={16} />{isEditorMode ? 'К дереву редактора' : 'К учебным курсам'}</Link>{canEdit && c && <Link to={`/editor/courses/${c.slug}`} className="btn-outline inline-flex items-center gap-2"><PencilLine size={16} />Редактировать этот курс</Link>}</div>
    {loading ? <div className="mt-6 rounded-[2rem] border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 p-10 text-center shadow-soft"><Loader2 className="mx-auto animate-spin text-brand-600" /><div className="mt-3 text-neutral-600 dark:text-neutral-300">Открываю раздел...</div></div> : error ? <div className="mt-6 rounded-3xl border border-red-200 bg-red-50 p-4 text-sm text-red-800 dark:border-red-900 dark:bg-red-950/20 dark:text-red-100">{error}</div> : c ? <>
      <nav className="mt-5 flex flex-wrap items-center gap-2 text-sm text-neutral-500 dark:text-neutral-400"><Link to={isEditorMode ? '/editor' : '/'}>CT</Link>{path.map((item) => <React.Fragment key={item.id}><ChevronRight size={15} /><Link to={href(item.slug)} className={item.slug === courseSlug ? 'font-semibold text-neutral-900 dark:text-neutral-100' : 'hover:text-brand-700 dark:hover:text-brand-200'}>{item.shortTitle || item.title}</Link></React.Fragment>)}</nav>
      <section className="mt-5 overflow-hidden rounded-[2rem] border border-neutral-200/80 dark:border-neutral-800 bg-white dark:bg-neutral-900 shadow-soft"><div className="bg-gradient-to-br from-brand-50 via-white to-white p-6 md:p-8 dark:from-brand-900/20 dark:via-neutral-900 dark:to-neutral-900"><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-brand-200 bg-white/80 px-3 py-1 text-sm font-semibold text-brand-800 dark:border-brand-800 dark:bg-neutral-950/60 dark:text-brand-100"><Sparkles size={16} />{typeLabel(c)}</div><h1 className="max-w-5xl text-4xl md:text-5xl font-bold tracking-tight">{c.title}</h1>{(c.summary || c.description) && <p className="mt-4 max-w-4xl text-lg leading-8 text-neutral-700 dark:text-neutral-200">{c.summary || c.description}</p>}<div className="mt-6 flex flex-wrap gap-3 text-sm">{c.subjectCode && <span className="rounded-full border border-neutral-200 bg-white/80 px-3 py-1 dark:border-neutral-800 dark:bg-neutral-950/60">Предмет: {c.subjectCode}</span>}{c.examCode && <span className="rounded-full border border-neutral-200 bg-white/80 px-3 py-1 dark:border-neutral-800 dark:bg-neutral-950/60">Экзамен: {c.examCode}</span>}{c.sectionCode && <span className="rounded-full border border-neutral-200 bg-white/80 px-3 py-1 dark:border-neutral-800 dark:bg-neutral-950/60">Раздел: {c.sectionCode}</span>}</div></div></section>
      {isEditorMode && <div className="mt-5 rounded-3xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900 dark:border-amber-900 dark:bg-amber-950/20 dark:text-amber-100">Режим редактора включён: дочерние карточки открываются в окне редактирования.</div>}
      {outline.children?.length > 0 && <section className="mt-6"><div className="mb-3 flex items-center gap-2"><BookOpen className="text-brand-600" /><h2 className="text-2xl font-bold tracking-tight">Внутри курса</h2></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{outline.children.map((child) => <Link key={child.id} to={href(child.slug)} className="group rounded-[2rem] border border-neutral-200/80 dark:border-neutral-800 bg-white dark:bg-neutral-900 p-5 shadow-soft transition hover:-translate-y-0.5 hover:border-brand-300"><div className="text-sm font-semibold uppercase tracking-wide text-brand-700 dark:text-brand-300">{typeLabel(child)}</div><h3 className="mt-2 text-2xl font-bold group-hover:text-brand-700 dark:group-hover:text-brand-200">{child.title}</h3>{child.summary && <p className="mt-2 line-clamp-3 leading-7 text-neutral-600 dark:text-neutral-300">{child.summary}</p>}<div className="mt-5 inline-flex items-center gap-2 font-semibold text-brand-700 dark:text-brand-200">{isEditorMode ? 'Редактировать' : 'Открыть'} <ChevronRight size={18} /></div></Link>)}</div></section>}
      {(outline.conspects?.length > 0 || c.sectionCode) && <section className="mt-6 grid gap-5 lg:grid-cols-[minmax(0,1.4fr)_minmax(320px,0.8fr)]"><div className="rounded-[2rem] border border-neutral-200/80 dark:border-neutral-800 bg-white dark:bg-neutral-900 p-5 shadow-soft"><div className="mb-4 flex items-center gap-2"><FileText className="text-brand-600" /><h2 className="text-2xl font-bold tracking-tight">Конспекты</h2></div>{outline.conspects?.length > 0 ? <div className="space-y-3">{outline.conspects.map((x) => <Link key={x.id} to={isEditorMode ? `/editor/courses/${c.slug}?conspect=${x.slug}` : `/courses/${c.slug}/conspects/${x.slug}`} className="block rounded-3xl border border-neutral-200 dark:border-neutral-800 bg-neutral-50 dark:bg-neutral-950 p-4 transition hover:border-brand-300"><div className="font-semibold text-lg">{x.title}</div>{x.lead && <p className="mt-1 line-clamp-2 text-sm leading-6 text-neutral-600 dark:text-neutral-300">{x.lead}</p>}<div className="mt-3 inline-flex items-center gap-2 text-sm font-semibold text-brand-700 dark:text-brand-200">{isEditorMode ? 'Редактировать конспект' : 'Открыть конспект'} <ChevronRight size={16} /></div></Link>)}</div> : <div className="rounded-3xl border border-dashed border-neutral-200 dark:border-neutral-800 p-6 text-neutral-500 dark:text-neutral-400">Для этого раздела конспекты ещё не добавлены.</div>}</div><div className="rounded-[2rem] border border-brand-200 dark:border-brand-800 bg-brand-50 dark:bg-brand-900/20 p-5 shadow-soft"><div className="mb-4 flex items-center gap-2"><ClipboardList className="text-brand-700 dark:text-brand-200" /><h2 className="text-2xl font-bold tracking-tight">Задания</h2></div>{c.sectionCode ? <><p className="leading-7 text-neutral-700 dark:text-neutral-200">Мини-задачи хранятся отдельно в quiz-task-service.</p><div className="mt-4 rounded-2xl border border-brand-200 dark:border-brand-800 bg-white dark:bg-neutral-900 p-4"><div className="text-sm text-neutral-500 dark:text-neutral-400">Сейчас в разделе</div><div className="text-3xl font-bold">{quizTasks.length}</div><div className="text-sm text-neutral-500 dark:text-neutral-400">опубликованных заданий</div></div><Link to={`/courses/${c.slug}/tasks${q ? `?${q}` : ''}`} className="btn-primary mt-4 inline-flex items-center gap-2"><PlayCircle size={18} />Перейти к заданиям</Link></> : <p className="leading-7 text-neutral-700 dark:text-neutral-200">Задания появляются внутри конкретных разделов экзамена.</p>}</div></section>}
    </> : null}
  </div></div></Layout>;
}
