#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"
ENV_FILE="${TASKFORGE_ENV_FILE:-.env}"
[ -f "$ENV_FILE" ] || { echo "Missing $ENV_FILE. Run ./scripts/setup/generate-secrets.sh first." >&2; exit 2; }

# The same wrapper is shipped both as a standalone server bundle and under
# deploy/prod inside the source repository. Keep runtime/config paths anchored
# to the real TaskForge root in both layouts.
if [ -f "$ROOT_DIR/cluster/compose.cluster.yaml" ]; then
  TASKFORGE_LAYOUT_ROOT="$ROOT_DIR"
  TASKFORGE_CLUSTER_DIR_DEFAULT="$ROOT_DIR/cluster"
elif [ -f "$ROOT_DIR/../cluster/compose.cluster.yaml" ]; then
  TASKFORGE_LAYOUT_ROOT="$(cd "$ROOT_DIR/../.." && pwd)"
  TASKFORGE_CLUSTER_DIR_DEFAULT="$(cd "$ROOT_DIR/../cluster" && pwd)"
else
  echo "Cannot determine TaskForge cluster layout from $ROOT_DIR" >&2
  exit 2
fi
export TASKFORGE_ROOT="${TASKFORGE_ROOT:-$TASKFORGE_LAYOUT_ROOT}"
TASKFORGE_CLUSTER_DIR="${TASKFORGE_CLUSTER_DIR:-$TASKFORGE_CLUSTER_DIR_DEFAULT}"
export TASKFORGE_CLUSTER_DIR

TASKFORGE_IMAGE_ANALYZER_MODEL_CACHE_DIR="${TASKFORGE_IMAGE_ANALYZER_MODEL_CACHE_DIR:-$TASKFORGE_ROOT/.runtime/image-analyzer-model-cache}"
mkdir -p "$TASKFORGE_IMAGE_ANALYZER_MODEL_CACHE_DIR" "$TASKFORGE_ROOT/.runtime"
chmod 0777 "$TASKFORGE_IMAGE_ANALYZER_MODEL_CACHE_DIR" 2>/dev/null || true
export TASKFORGE_IMAGE_ANALYZER_MODEL_CACHE_DIR
export TASKFORGE_POSTGRES_INIT_DIR="${TASKFORGE_POSTGRES_INIT_DIR:-$TASKFORGE_ROOT/infrastructure/postgres/init}"
export TASKFORGE_INVENTORY="${TASKFORGE_INVENTORY:-$TASKFORGE_CLUSTER_DIR/inventory.json}"
export TASKFORGE_CLUSTER_CONFIG="${TASKFORGE_CLUSTER_CONFIG:-$TASKFORGE_CLUSTER_DIR/cluster.json}"
CLUSTER_RUNTIME="$TASKFORGE_ROOT/.runtime/cluster"

# Node-local settings are generated outside the shared .env.
# Exported shell values override --env-file interpolation.
for local_env in "$CLUSTER_RUNTIME/local.env" "$CLUSTER_RUNTIME/cpu.env" "$CLUSTER_RUNTIME/app-routing.env"; do
  if [ -f "$local_env" ]; then
    set -a
    . "$local_env"
    set +a
  fi
done

COMPOSE_FILES=(
  -f "$ROOT_DIR/compose/00-storage.yaml"
  -f "$ROOT_DIR/compose/10-apps-gateway.yaml"
  -f "$ROOT_DIR/compose/20-core-services.yaml"
  -f "$ROOT_DIR/compose/30-execution.yaml"
  -f "$ROOT_DIR/compose/40-ai-and-analyzers.yaml"
  -f "$ROOT_DIR/compose/50-integrations.yaml"
  -f "$ROOT_DIR/compose/80-watchtower.yaml"
  -f "$ROOT_DIR/compose/90-certbot.yaml"
)

CLUSTER_ENABLED=false
if [ -f "$CLUSTER_RUNTIME/enabled" ] || [ "${TASKFORGE_CLUSTER_FORCE:-0}" = "1" ]; then
  CLUSTER_ENABLED=true
  NODE_ENV="$CLUSTER_RUNTIME/node.env"
  [ -f "$NODE_ENV" ] || { echo "Missing $NODE_ENV. Run ./cluster/ops/quorum/set-node.sh NODE_ID first." >&2; exit 2; }
  set -a
  # Generated by clusterctl.py from validated topology; contains simple KEY=value lines.
  . "$NODE_ENV"
  set +a
  export TASKFORGE_CLUSTER_ENABLED=true
  COMPOSE_FILES+=( -f "$TASKFORGE_CLUSTER_DIR/compose.cluster.yaml" )
fi

# Watchtower must receive registry credentials when GHCR packages are private.
AUTH_CONFIG_PATH=""
LOCAL_DOCKER_CONFIG=""
if [ -f "$ROOT_DIR/config.json" ]; then LOCAL_DOCKER_CONFIG="$ROOT_DIR/config.json";
elif [ -f "$TASKFORGE_ROOT/config.json" ]; then LOCAL_DOCKER_CONFIG="$TASKFORGE_ROOT/config.json"; fi
if [ -n "$LOCAL_DOCKER_CONFIG" ]; then
  mkdir -p "$TASKFORGE_ROOT/.docker"
  cp "$LOCAL_DOCKER_CONFIG" "$TASKFORGE_ROOT/.docker/config.json"
  chmod 600 "$TASKFORGE_ROOT/.docker/config.json" 2>/dev/null || true
  export DOCKER_CONFIG="$TASKFORGE_ROOT/.docker"
  AUTH_CONFIG_PATH="$TASKFORGE_ROOT/.docker/config.json"
elif [ -n "${DOCKER_CONFIG:-}" ] && [ -f "${DOCKER_CONFIG}/config.json" ]; then
  AUTH_CONFIG_PATH="$(cd "$(dirname "${DOCKER_CONFIG}/config.json")" && pwd)/config.json"
elif [ -f "${HOME:-}/.docker/config.json" ]; then
  AUTH_CONFIG_PATH="$(cd "$(dirname "${HOME}/.docker/config.json")" && pwd)/config.json"
fi

if [ -n "$AUTH_CONFIG_PATH" ]; then
  python3 - "$TASKFORGE_ROOT/.runtime/watchtower-auth.yaml" "$AUTH_CONFIG_PATH" <<'PY'
from pathlib import Path
import json,sys
Path(sys.argv[1]).write_text(
    "services:\n  watchtower:\n    volumes:\n      - " + json.dumps(sys.argv[2]+":/config.json:ro") + "\n",
    encoding="utf-8",
)
PY
  COMPOSE_FILES+=( -f "$TASKFORGE_ROOT/.runtime/watchtower-auth.yaml" )
fi

compose(){
  local profile_args=()
  if [ "$CLUSTER_ENABLED" = true ] && [ "${CLUSTER_DCS_VOTER:-false}" = true ]; then
    profile_args+=( --profile dcs-voter )
  fi
  docker compose --env-file "$ENV_FILE" "${profile_args[@]}" "${COMPOSE_FILES[@]}" "$@"
}

profile_pull_services(){
  local node_file="$CLUSTER_RUNTIME/node-id" cfg="$TASKFORGE_CLUSTER_CONFIG"
  local -a all_services=()
  mapfile -t all_services < <(compose config --services)
  [ "${#all_services[@]}" -gt 0 ] || return 0

  # Before a node is assigned, retain the traditional full pull behaviour.
  if [ ! -s "$node_file" ] || [ ! -s "$cfg" ]; then
    printf '%s\n' "${all_services[@]}"
    return 0
  fi

  python3 - "$cfg" "$(tr -d '\r\n' < "$node_file")" "${all_services[@]}" <<'PY_PROFILE_PULL'
import json,sys
cfg_path,node_id,*services=sys.argv[1:]
try:
    cfg=json.load(open(cfg_path,encoding='utf-8'))
    node=next(n for n in cfg.get('nodes',[]) if str(n.get('id'))==node_id)
except Exception:
    print(*services,sep='\n')
    raise SystemExit(0)
app=node.get('app') or {}
profile=str(app.get('profile') or 'full').lower()
excluded={str(x) for x in app.get('exclude_services',[]) if str(x)}
control={'postgres','etcd','rabbitmq','redis','minio','watchtower','certbot'}
if profile == 'none':
    selected=[s for s in services if s in control]
elif profile == 'lite':
    selected=[s for s in services if s not in excluded]
else:
    selected=services
print(*selected,sep='\n')
PY_PROFILE_PULL
}

profile_pull(){
  local -a services=()
  mapfile -t services < <(profile_pull_services)
  [ "${#services[@]}" -gt 0 ] || { echo 'No services assigned to this node profile.'; return 0; }
  echo "Profile-aware pull: ${services[*]}"
  compose pull "${services[@]}"
}

new_log_dir(){
  local base="${TASKFORGE_LOG_DIR:-$TASKFORGE_ROOT/.runtime/logs}"
  local dir="$base/$(date -u +%Y%m%d-%H%M%S)"
  mkdir -p "$dir"
  printf '%s\n' "$dir"
}

capture_window(){
  local seconds="$1" dir="$2" start="$3"
  local log="$dir/startup-${seconds}s.log"
  {
    echo "TaskForge live/develop startup log"
    echo "Started at UTC: $start"
    echo "Capture seconds: $seconds"
    echo "Environment file: $ENV_FILE"
    echo "Cluster mode: $CLUSTER_ENABLED"
    echo "============================================================"
  } > "$log"
  echo "Capturing ${seconds}s of logs into $log"
  if command -v timeout >/dev/null 2>&1; then
    (timeout "${seconds}s" "$0" logs --since "$start" --timestamps -f 2>&1 || true) | tee -a "$log"
  else
    ( "$0" logs --since "$start" --timestamps -f 2>&1 & pid=$!; sleep "$seconds"; kill "$pid" 2>/dev/null || true; wait "$pid" 2>/dev/null || true ) | tee -a "$log"
  fi
  compose ps > "$dir/ps.txt" 2>&1 || true
}

case "${1:-}" in
  pull-plan)
    profile_pull_services
    ;;
  pull)
    shift
    if [ "$#" -eq 0 ]; then
      profile_pull
    else
      # Explicit service lists/options are an intentional operator override.
      compose pull "$@"
    fi
    ;;
  up-logs|up-capture|up-watch)
    shift
    seconds="${TASKFORGE_STARTUP_LOG_SECONDS:-30}"
    start="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    dir="$(new_log_dir)"
    compose up -d "$@"
    capture_window "$seconds" "$dir" "$start"
    ;;
  logs-startup|logs-window)
    shift
    seconds="${1:-${TASKFORGE_STARTUP_LOG_SECONDS:-30}}"
    case "$seconds" in ''|*[!0-9]*) echo "error: duration must be numeric" >&2; exit 2;; esac
    capture_window "$seconds" "$(new_log_dir)" "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    ;;
  logs-dump)
    shift
    lines="${1:-${TASKFORGE_LOG_TAIL:-1000}}"
    case "$lines" in ''|*[!0-9]*) echo "error: line count must be numeric" >&2; exit 2;; esac
    shift || true
    dir="$(new_log_dir)"
    compose logs --timestamps --tail "$lines" "$@" > "$dir/logs-tail-${lines}.log" 2>&1 || true
    compose ps > "$dir/ps.txt" 2>&1 || true
    echo "Saved logs: $dir"
    ;;
  *) compose "$@" ;;
esac
