plugins {
    id 'java'
}

group = 'com.taskforge'
version = '1.8.0'

def targetJava = 25
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(targetJava)
    }
}

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
}

dependencies {
    compileOnly 'dev.folia:folia-api:26.1.2.build.8-stable'
    compileOnly 'com.google.code.gson:gson:2.14.0'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release.set(targetJava)
}
