# TaskForge compose module: edge.yaml
services:
  nginx:
    build:
      context: ./nginx
    container_name: taskforge-nginx
    environment:
    - DOMAIN=${DOMAIN}
    - CT_DOMAIN=${CT_DOMAIN}
    depends_on:
    - front
    - front-ct
    - api
    - learning-content-service
    - quiz-task-service
    volumes:
    - certbot-www:/var/www/certbot
    - letsencrypt:/etc/letsencrypt
    ports:
    - 80:80
    - 443:443
    networks:
    - appnet
    restart: unless-stopped
  certbot-init:
    image: certbot/certbot:latest
    container_name: taskforge-certbot-init
    environment:
    - DOMAIN=${DOMAIN}
    - CT_DOMAIN=${CT_DOMAIN}
    - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
    - certbot-www:/var/www/certbot
    - letsencrypt:/etc/letsencrypt
    depends_on:
    - nginx
    entrypoint:
    - sh
    - -c
    - |
      certbot certonly \
        --webroot -w /var/www/certbot \
        --cert-name "$DOMAIN" \
        -d "$DOMAIN" \
        -d "$CT_DOMAIN" \
        --email "$LETSENCRYPT_EMAIL" \
        --rsa-key-size 4096 --agree-tos --no-eff-email --non-interactive --expand --keep-until-expiring
    restart: 'no'
    networks:
    - appnet
  certbot-renew:
    image: certbot/certbot:latest
    container_name: taskforge-certbot-renew
    environment:
    - DOMAIN=${DOMAIN}
    - CT_DOMAIN=${CT_DOMAIN}
    volumes:
    - certbot-www:/var/www/certbot
    - letsencrypt:/etc/letsencrypt
    depends_on:
    - nginx
    entrypoint:
    - sh
    - -c
    - "trap : TERM INT\nwhile :; do\n  certbot renew --webroot -w /var/www/certbot\
      \ --quiet\n  sleep 12h\ndone\n"
    restart: unless-stopped
    networks:
    - appnet
volumes:
  certbot-www: null
  letsencrypt: null
