# TaskForge compose module: ops.yaml
services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: taskforge-watchtower
    command: --interval 60 --cleanup --label-enable --revive-stopped --warn-on-head-failure=auto
    environment:
    - DOCKER_CONFIG=/config
    - WATCHTOWER_NOTIFICATIONS_LEVEL=info
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /home/pivasya/Desktop/taskforge-prod-linux/config.json:/config/config.json:ro
    networks:
    - appnet
    restart: unless-stopped
