from __future__ import annotations

SCENARIO_DEFINITIONS = [
    {
        "id": "step-by-step-ladder",
        "name": "Лесенка",
        "family": "progression",
        "default_mode": "guided-sequence",
        "default_count": 5,
        "prefer_guided": True,
        "prefer_tiny_steps": True,
        "force_small_programs": True,
        "require_explicit_if": False,
        "prefer_single_deep_task": False,
        "prefer_course_audit": False,
        "assistant_silence_priority": True,
        "aliases": ["лесенк", "пошаг", "шаг за шаг", "с нуля", "первые шаги", "маленьких программ", "серия маленьких"],
        "anti": ["одну сложную", "без разжёвывания"],
    },
    {
        "id": "new-topic-intro", "name": "Новая тема", "family": "topic", "default_mode": "topic-pack", "default_count": 3,
        "prefer_guided": True, "prefer_tiny_steps": False, "force_small_programs": False, "require_explicit_if": False,
        "prefer_single_deep_task": False, "prefer_course_audit": True, "assistant_silence_priority": True,
        "aliases": ["новая тема", "ввести тему", "начать тему", "вход в тему", "introduce topic"], "anti": ["расширение", "углубить"],
    },
    {
        "id": "topic-expansion", "name": "Расширение старой темы", "family": "topic", "default_mode": "topic-pack", "default_count": 3,
        "prefer_guided": False, "prefer_tiny_steps": False, "force_small_programs": False, "require_explicit_if": False,
        "prefer_single_deep_task": False, "prefer_course_audit": False, "assistant_silence_priority": True,
        "aliases": ["расширение", "углубить", "продолжить тему", "расширить тему", "докрутить тему"], "anti": ["новая тема"],
    },
    {
        "id": "course-gap-audit", "name": "Проверка курса на дырки", "family": "audit", "default_mode": "topic-pack", "default_count": 3,
        "prefer_guided": False, "prefer_tiny_steps": False, "force_small_programs": False, "require_explicit_if": False,
        "prefer_single_deep_task": False, "prefer_course_audit": True, "assistant_silence_priority": True,
        "aliases": ["дырки", "пробелы", "проверь курс", "аудит курса", "что пропущено", "gap audit"], "anti": ["сгенерируй сразу"],
    },
    {
        "id": "reorder-auto", "name": "Перестановка как нейронка", "family": "reordering", "default_mode": "topic-pack", "default_count": 1,
        "prefer_guided": False, "prefer_tiny_steps": False, "force_small_programs": False, "require_explicit_if": False,
        "prefer_single_deep_task": False, "prefer_course_audit": True, "assistant_silence_priority": True,
        "aliases": ["перестановка", "переупорядоч", "как нейронка", "как ai", "авто порядок"], "anti": ["как человек скажет"],
    },
    {
        "id": "reorder-manual", "name": "Перестановка как скажет человек", "family": "reordering", "default_mode": "topic-pack", "default_count": 1,
        "prefer_guided": False, "prefer_tiny_steps": False, "force_small_programs": False, "require_explicit_if": False,
        "prefer_single_deep_task": False, "prefer_course_audit": False, "assistant_silence_priority": True,
        "aliases": ["как человек скажет", "строго по моему порядку", "manual reorder", "по моей команде переставь"], "anti": ["как нейронка"],
    },
    {
        "id": "split-heavy-topic", "name": "Разрезать сложную тему", "family": "structure", "default_mode": "topic-pack", "default_count": 3,
        "prefer_guided": True, "prefer_tiny_steps": True, "force_small_programs": False, "require_explicit_if": False,
        "prefer_single_deep_task": False, "prefer_course_audit": False, "assistant_silence_priority": True,
        "aliases": ["разбить тему", "слишком сложно", "разрезать", "дробить", "split topic"], "anti": ["объединить"],
    },
    {
        "id": "compress-stretched-topic", "name": "Сжать растянутую тему", "family": "structure", "default_mode": "topic-pack", "default_count": 1,
        "prefer_guided": False, "prefer_tiny_steps": False, "force_small_programs": False, "require_explicit_if": False,
        "prefer_single_deep_task": False, "prefer_course_audit": False, "assistant_silence_priority": True,
        "aliases": ["сжать", "объединить задачи", "слишком растянуто", "compress topic"], "anti": ["разбить", "дробить"],
    },
    {
        "id": "pretopic-bridges", "name": "Подводка к теме", "family": "transition", "default_mode": "bridge-pack", "default_count": 5,
        "prefer_guided": True, "prefer_tiny_steps": True, "force_small_programs": False, "require_explicit_if": False,
        "prefer_single_deep_task": False, "prefer_course_audit": True, "assistant_silence_priority": True,
        "aliases": ["мостик", "bridge", "подводящ", "перед темой", "до темы", "подвести к теме"], "anti": ["после темы"],
    },
    {
        "id": "posttopic-reinforcement", "name": "Закрепление после темы", "family": "transition", "default_mode": "topic-pack", "default_count": 4,
        "prefer_guided": True, "prefer_tiny_steps": False, "force_small_programs": False, "require_explicit_if": False,
        "prefer_single_deep_task": False, "prefer_course_audit": False, "assistant_silence_priority": True,
        "aliases": ["после темы", "закрепление", "после блока", "reinforcement", "закрепить"], "anti": ["до темы"],
    },
    {
        "id": "spaced-repetition", "name": "Повторение темы позже", "family": "progression", "default_mode": "topic-pack", "default_count": 3,
        "prefer_guided": False, "prefer_tiny_steps": False, "force_small_programs": False, "require_explicit_if": False,
        "prefer_single_deep_task": False, "prefer_course_audit": False, "assistant_silence_priority": True,
        "aliases": ["повторить позже", "вернуть тему", "спустя несколько уроков", "spaced repetition"], "anti": [],
    },
    {
        "id": "topic-transition", "name": "Переход между темами", "family": "transition", "default_mode": "bridge-pack", "default_count": 3,
        "prefer_guided": True, "prefer_tiny_steps": False, "force_small_programs": False, "require_explicit_if": False,
        "prefer_single_deep_task": False, "prefer_course_audit": True, "assistant_silence_priority": True,
        "aliases": ["переход между темами", "стык тем", "между темами", "transition between"], "anti": [],
    },
    {
        "id": "restore-sequence", "name": "Восстановление последовательности", "family": "structure", "default_mode": "topic-pack", "default_count": 3,
        "prefer_guided": False, "prefer_tiny_steps": False, "force_small_programs": False, "require_explicit_if": False,
        "prefer_single_deep_task": False, "prefer_course_audit": True, "assistant_silence_priority": True,
        "aliases": ["сломанная последовательность", "восстановить порядок", "broken sequence", "исправить последовательность"], "anti": [],
    },
    {
        "id": "fill-course-gap", "name": "Заполнение пустого участка", "family": "structure", "default_mode": "bridge-pack", "default_count": 3,
        "prefer_guided": True, "prefer_tiny_steps": False, "force_small_programs": False, "require_explicit_if": False,
        "prefer_single_deep_task": False, "prefer_course_audit": True, "assistant_silence_priority": True,
        "aliases": ["заполнить пустой участок", "между заданиями", "скачок", "fill gap"], "anti": [],
    },
    {
        "id": "single-deep-task", "name": "Одна сложная задача", "family": "difficulty", "default_mode": "single-draft", "default_count": 1,
        "prefer_guided": False, "prefer_tiny_steps": False, "force_small_programs": False, "require_explicit_if": False,
        "prefer_single_deep_task": True, "prefer_course_audit": False, "assistant_silence_priority": True,
        "aliases": ["одну сложную", "одну сильную", "без разжёвывания", "посложнее", "deep task", "challenge"], "anti": ["лесенк", "несколько маленьких"],
    },
    {
        "id": "advanced-pack", "name": "Пакет сложных задач", "family": "difficulty", "default_mode": "topic-pack", "default_count": 3,
        "prefer_guided": False, "prefer_tiny_steps": False, "force_small_programs": False, "require_explicit_if": False,
        "prefer_single_deep_task": False, "prefer_course_audit": False, "assistant_silence_priority": True,
        "aliases": ["пакет сложных", "несколько сложных", "advanced pack", "сложные задачи"], "anti": ["пошаг", "с нуля"],
    },
    {
        "id": "difficulty-smoothing", "name": "Выравнивание сложности", "family": "difficulty", "default_mode": "topic-pack", "default_count": 3,
        "prefer_guided": False, "prefer_tiny_steps": False, "force_small_programs": False, "require_explicit_if": False,
        "prefer_single_deep_task": False, "prefer_course_audit": True, "assistant_silence_priority": True,
        "aliases": ["выравнивание сложности", "скачок сложности", "сделай плавнее", "difficulty smoothing"], "anti": [],
    },
    {
        "id": "difficulty-raise", "name": "Повышение сложности", "family": "difficulty", "default_mode": "topic-pack", "default_count": 3,
        "prefer_guided": False, "prefer_tiny_steps": False, "force_small_programs": False, "require_explicit_if": False,
        "prefer_single_deep_task": False, "prefer_course_audit": False, "assistant_silence_priority": True,
        "aliases": ["поднять сложность", "усложнить", "harder", "сделай взрослее"], "anti": ["упрости"],
    },
    {
        "id": "difficulty-lower", "name": "Упрощение блока", "family": "difficulty", "default_mode": "topic-pack", "default_count": 3,
        "prefer_guided": True, "prefer_tiny_steps": True, "force_small_programs": False, "require_explicit_if": False,
        "prefer_single_deep_task": False, "prefer_course_audit": False, "assistant_silence_priority": True,
        "aliases": ["упрости", "понизить сложность", "слишком сложно для новичка", "make easier"], "anti": ["усложнить"],
    },
    {
        "id": "milestone-checkpoint", "name": "Контрольная точка", "family": "assessment", "default_mode": "topic-pack", "default_count": 1,
        "prefer_guided": False, "prefer_tiny_steps": False, "force_small_programs": False, "require_explicit_if": False,
        "prefer_single_deep_task": False, "prefer_course_audit": False, "assistant_silence_priority": True,
        "aliases": ["контрольная", "milestone", "проверочная", "checkpoint", "контрольная точка"], "anti": [],
    },
    {
        "id": "micro-program-series", "name": "Серия маленьких программ", "family": "pedagogy", "default_mode": "guided-sequence", "default_count": 5,
        "prefer_guided": True, "prefer_tiny_steps": True, "force_small_programs": True, "require_explicit_if": False,
        "prefer_single_deep_task": False, "prefer_course_audit": False, "assistant_silence_priority": True,
        "aliases": ["несколько программ", "маленькие программы", "мини программы", "series of programs", "практических мини", "как использовать if", "как пользоваться if", "освоение if", "самому if"],
        "anti": ["одну сложную"],
    },
    {
        "id": "story-driven-task", "name": "Сюжетная задача", "family": "pedagogy", "default_mode": "single-draft", "default_count": 1,
        "prefer_guided": False, "prefer_tiny_steps": False, "force_small_programs": False, "require_explicit_if": False,
        "prefer_single_deep_task": False, "prefer_course_audit": False, "assistant_silence_priority": True,
        "aliases": ["сюжетную", "история", "story task", "сценарную задачу"], "anti": [],
    },
    {
        "id": "comparison-learning", "name": "Обучение через сравнение", "family": "pedagogy", "default_mode": "topic-pack", "default_count": 2,
        "prefer_guided": False, "prefer_tiny_steps": False, "force_small_programs": False, "require_explicit_if": False,
        "prefer_single_deep_task": False, "prefer_course_audit": False, "assistant_silence_priority": True,
        "aliases": ["через сравнение", "сравнить подходы", "compare approaches", "сопоставь"], "anti": [],
    },
    {
        "id": "common-mistakes", "name": "Обучение через ошибки", "family": "pedagogy", "default_mode": "topic-pack", "default_count": 3,
        "prefer_guided": False, "prefer_tiny_steps": False, "force_small_programs": False, "require_explicit_if": False,
        "prefer_single_deep_task": False, "prefer_course_audit": False, "assistant_silence_priority": True,
        "aliases": ["типичные ошибки", "частые ошибки", "ловить ошибки", "common mistakes"], "anti": [],
    },
    {
        "id": "remediation-pack", "name": "Добивание слабых мест", "family": "pedagogy", "default_mode": "topic-pack", "default_count": 4,
        "prefer_guided": True, "prefer_tiny_steps": False, "force_small_programs": False, "require_explicit_if": False,
        "prefer_single_deep_task": False, "prefer_course_audit": True, "assistant_silence_priority": True,
        "aliases": ["добить слабые места", "remediation", "исправить слабые места", "закрыть пробелы"], "anti": [],
    },
    {
        "id": "restyle-explanation", "name": "Переобъяснение темы", "family": "pedagogy", "default_mode": "single-draft", "default_count": 1,
        "prefer_guided": True, "prefer_tiny_steps": False, "force_small_programs": False, "require_explicit_if": False,
        "prefer_single_deep_task": False, "prefer_course_audit": False, "assistant_silence_priority": True,
        "aliases": ["объясни иначе", "другим стилем", "переобъясни", "restyle"], "anti": [],
    },
    {
        "id": "theory-to-practice", "name": "Превратить теорию в задачи", "family": "format", "default_mode": "topic-pack", "default_count": 3,
        "prefer_guided": True, "prefer_tiny_steps": False, "force_small_programs": False, "require_explicit_if": False,
        "prefer_single_deep_task": False, "prefer_course_audit": False, "assistant_silence_priority": True,
        "aliases": ["из теории в задачи", "преврати теорию", "theory to practice"], "anti": [],
    },
    {
        "id": "practice-to-theory", "name": "Превратить задачи в теорию", "family": "format", "default_mode": "single-draft", "default_count": 1,
        "prefer_guided": False, "prefer_tiny_steps": False, "force_small_programs": False, "require_explicit_if": False,
        "prefer_single_deep_task": False, "prefer_course_audit": False, "assistant_silence_priority": True,
        "aliases": ["из задач в теорию", "practice to theory", "конспект по задачам"], "anti": [],
    },
    {
        "id": "programming-quiz", "name": "Тесты по программированию", "family": "tests", "default_mode": "topic-pack", "default_count": 10,
        "prefer_guided": False, "prefer_tiny_steps": False, "force_small_programs": False, "require_explicit_if": False,
        "prefer_single_deep_task": False, "prefer_course_audit": False, "assistant_silence_priority": True,
        "aliases": ["тесты", "quiz", "варианты ответов", "выбор ответа", "по программированию"], "anti": ["русскому языку"],
    },
    {
        "id": "russian-language-tests", "name": "Тесты по русскому языку", "family": "tests", "default_mode": "topic-pack", "default_count": 10,
        "prefer_guided": False, "prefer_tiny_steps": False, "force_small_programs": False, "require_explicit_if": False,
        "prefer_single_deep_task": False, "prefer_course_audit": False, "assistant_silence_priority": True,
        "aliases": ["русский язык", "по русскому", "орфография", "пунктуация", "генерация тестов по русскому языку"], "anti": ["c++", "программированию"],
    },
    {
        "id": "general-topic-pack", "name": "Общий пакет задач", "family": "general", "default_mode": "topic-pack", "default_count": 3,
        "prefer_guided": False, "prefer_tiny_steps": False, "force_small_programs": False, "require_explicit_if": False,
        "prefer_single_deep_task": False, "prefer_course_audit": False, "assistant_silence_priority": True,
        "aliases": ["задач", "упражнен", "practice"], "anti": [],
    },
]

SCENARIO_BY_ID = {item["id"]: item for item in SCENARIO_DEFINITIONS}
