// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskForge.Tasks.Api.Data;

#nullable disable

namespace TaskForge.Tasks.Api.Migrations
{
    [DbContext(typeof(TasksDbContext))]
    [Migration("20260909054604_AddSqlDomain")]
    partial class AddSqlDomain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskForge.Tasks.Api.Domain.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllowedLanguagesCsv")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("AnalyticsSettingsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("CodeForbiddenCallsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("CodeRequiredCallsJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("Sort")
                        .HasColumnType("integer");

                    b.Property<string>("StarterCode")
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("TestsJson")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "Sort");

                    b.ToTable("Assignments", (string)null);
                });

            modelBuilder.Entity("TaskForge.Tasks.Api.Domain.AssignmentActivityEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("ActiveDurationMs")
                        .HasColumnType("bigint");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<long?>("BlurDurationMs")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ClientTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CodeDelta")
                        .HasColumnType("integer");

                    b.Property<string>("CodeHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("CodeLength")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("EventUid")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<long?>("HiddenDurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("IpHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Language")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("RiskPoints")
                        .HasColumnType("integer");

                    b.Property<string>("RiskReason")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid?>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TextHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("TextLength")
                        .HasColumnType("integer");

                    b.Property<string>("TextSample")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("UserAgentHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId", "CreatedAt");

                    b.HasIndex("AssignmentId", "EventType", "CreatedAt");

                    b.HasIndex("AssignmentId", "UserId", "SessionId", "CreatedAt");

                    b.HasIndex("AssignmentId", "UserId", "SessionId", "EventUid")
                        .IsUnique();

                    b.ToTable("AssignmentActivityEvents", (string)null);
                });

            modelBuilder.Entity("TaskForge.Tasks.Api.Domain.AssignmentCodeSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<int?>("CodeDelta")
                        .HasColumnType("integer");

                    b.Property<string>("CodeHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("CodeLength")
                        .HasColumnType("integer");

                    b.Property<string>("CodeSample")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullCode")
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid?>("RelatedEventId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RelatedSubmissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId", "CodeHash");

                    b.HasIndex("AssignmentId", "SessionId", "CreatedAt");

                    b.HasIndex("AssignmentId", "UserId", "CreatedAt");

                    b.ToTable("AssignmentCodeSnapshots", (string)null);
                });

            modelBuilder.Entity("TaskForge.Tasks.Api.Domain.AssignmentWorkSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ActiveDurationMs")
                        .HasColumnType("bigint");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("BlurCount")
                        .HasColumnType("integer");

                    b.Property<long>("BlurDurationMs")
                        .HasColumnType("bigint");

                    b.Property<int>("CloseCount")
                        .HasColumnType("integer");

                    b.Property<int>("CodeChangeCount")
                        .HasColumnType("integer");

                    b.Property<int>("CopyCount")
                        .HasColumnType("integer");

                    b.Property<int>("CutCount")
                        .HasColumnType("integer");

                    b.Property<int>("FailedSubmitCount")
                        .HasColumnType("integer");

                    b.Property<string>("FinalCodeHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("FinalCodeLength")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FocusCount")
                        .HasColumnType("integer");

                    b.Property<int>("FullscreenExitCount")
                        .HasColumnType("integer");

                    b.Property<int>("HiddenCount")
                        .HasColumnType("integer");

                    b.Property<long>("HiddenDurationMs")
                        .HasColumnType("bigint");

                    b.Property<int>("LanguageChangeCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastEventType")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("LastLanguage")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("MaxCodeLength")
                        .HasColumnType("integer");

                    b.Property<int>("OpenCount")
                        .HasColumnType("integer");

                    b.Property<int>("PassedSubmitCount")
                        .HasColumnType("integer");

                    b.Property<int>("PasteCount")
                        .HasColumnType("integer");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RiskReasonsJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("RiskScore")
                        .HasColumnType("integer");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SubmitCount")
                        .HasColumnType("integer");

                    b.Property<long>("TotalDurationMs")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("VisibleCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId", "LastActivityAt");

                    b.HasIndex("AssignmentId", "RiskScore");

                    b.HasIndex("AssignmentId", "UserId", "SessionId")
                        .IsUnique();

                    b.ToTable("AssignmentWorkSessions", (string)null);
                });

            modelBuilder.Entity("TaskForge.Tasks.Api.Domain.ServiceSchemaMarker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.ToTable("ServiceSchemaMarkers", (string)null);
                });

            modelBuilder.Entity("TaskForge.Tasks.Api.Domain.Sql.SqlAssignmentEngineTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("EngineProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenceSqlOverride")
                        .HasMaxLength(100000)
                        .HasColumnType("character varying(100000)");

                    b.Property<string>("ResultComparisonSettingsOverrideJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("SchemaCheckSettingsOverrideJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("Sort")
                        .HasColumnType("integer");

                    b.Property<Guid>("SpecVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("StarterSqlOverride")
                        .HasMaxLength(100000)
                        .HasColumnType("character varying(100000)");

                    b.Property<string>("StateCheckSettingsOverrideJson")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("EngineProfileId");

                    b.HasIndex("SpecVersionId", "EngineProfileId")
                        .IsUnique();

                    b.ToTable("SqlAssignmentEngineTargets", null, t =>
                        {
                            t.HasCheckConstraint("CK_SqlEngineTargets_Sort", "\"Sort\" >= 0");
                        });
                });

            modelBuilder.Entity("TaskForge.Tasks.Api.Domain.Sql.SqlAssignmentSpec", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DraftVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PublishedVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AssignmentId");

                    b.HasIndex("AssignmentId", "DraftVersionId");

                    b.HasIndex("AssignmentId", "PublishedVersionId");

                    b.ToTable("SqlAssignmentSpecs", (string)null);
                });

            modelBuilder.Entity("TaskForge.Tasks.Api.Domain.Sql.SqlAssignmentSpecVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowMultipleStatements")
                        .HasColumnType("boolean");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("ContractVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DatasetVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("LimitsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ReferenceSql")
                        .HasMaxLength(100000)
                        .HasColumnType("character varying(100000)");

                    b.Property<string>("ResultComparisonSettingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SchemaCheckSettingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SpecHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("StarterSql")
                        .HasMaxLength(100000)
                        .HasColumnType("character varying(100000)");

                    b.Property<string>("StateCheckSettingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("VerifierVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DatasetVersionId");

                    b.HasIndex("SpecHash");

                    b.HasIndex("AssignmentId", "Version")
                        .IsUnique();

                    b.ToTable("SqlAssignmentSpecVersions", null, t =>
                        {
                            t.HasCheckConstraint("CK_SqlSpecVersions_Hash", "\"SpecHash\" ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("CK_SqlSpecVersions_Mode", "\"Mode\" IN ('result', 'state', 'schema')");

                            t.HasCheckConstraint("CK_SqlSpecVersions_Version", "\"Version\" > 0 AND \"ContractVersion\" > 0");
                        });
                });

            modelBuilder.Entity("TaskForge.Tasks.Api.Domain.Sql.SqlDataset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessScope")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("AccessScope", "IsArchived");

                    b.ToTable("SqlDatasets", null, t =>
                        {
                            t.HasCheckConstraint("CK_SqlDatasets_Owner", "(\"AccessScope\" <> 'private' OR \"OwnerUserId\" IS NOT NULL) AND (\"OwnerUserId\" IS NULL OR \"OwnerUserId\" <> '00000000-0000-0000-0000-000000000000'::uuid)");

                            t.HasCheckConstraint("CK_SqlDatasets_Scope", "\"AccessScope\" IN ('private', 'editor-library')");
                        });
                });

            modelBuilder.Entity("TaskForge.Tasks.Api.Domain.Sql.SqlDatasetEngineValidation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DatasetVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("DiagnosticJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("EngineProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ExecutionJobId")
                        .HasColumnType("uuid");

                    b.Property<string>("MaterializationKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ValidationRunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EngineProfileId");

                    b.HasIndex("ExecutionJobId");

                    b.HasIndex("MaterializationKey");

                    b.HasIndex("DatasetVersionId", "EngineProfileId")
                        .IsUnique();

                    b.HasIndex("Status", "UpdatedAt");

                    b.ToTable("SqlDatasetEngineValidations", null, t =>
                        {
                            t.HasCheckConstraint("CK_SqlDatasetValidations_Key", "\"MaterializationKey\" ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("CK_SqlDatasetValidations_Status", "\"Status\" IN ('pending', 'validating', 'valid', 'invalid')");

                            t.HasCheckConstraint("CK_SqlDatasetValidations_Valid", "\"Status\" <> 'valid' OR (\"ValidatedAt\" IS NOT NULL AND \"ErrorCode\" IS NULL)");
                        });
                });

            modelBuilder.Entity("TaskForge.Tasks.Api.Domain.Sql.SqlDatasetVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DatasetId")
                        .HasColumnType("uuid");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("DefinitionSchemaVersion")
                        .HasColumnType("integer");

                    b.Property<string>("EngineOverridesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SeedJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("DatasetId", "Version")
                        .IsUnique();

                    b.ToTable("SqlDatasetVersions", null, t =>
                        {
                            t.HasCheckConstraint("CK_SqlDatasetVersions_Hash", "\"ContentHash\" ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("CK_SqlDatasetVersions_Version", "\"Version\" > 0 AND \"DefinitionSchemaVersion\" > 0");
                        });
                });

            modelBuilder.Entity("TaskForge.Tasks.Api.Domain.Sql.SqlEngineProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdapterVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("EngineVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<string>("RuntimeDigest")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("character varying(71)");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("SettingsSchemaVersion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint")
                        .IsUnique();

                    b.HasIndex("Key", "Revision")
                        .IsUnique();

                    b.ToTable("SqlEngineProfiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_SqlEngineProfiles_Fingerprint", "\"Fingerprint\" ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("CK_SqlEngineProfiles_RuntimeDigest", "\"RuntimeDigest\" ~ '^sha256:[0-9a-f]{64}$'");

                            t.HasCheckConstraint("CK_SqlEngineProfiles_Version", "\"Revision\" > 0 AND \"SettingsSchemaVersion\" > 0");
                        });
                });

            modelBuilder.Entity("TaskForge.Tasks.Api.Domain.Sql.SqlExpectedArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArtifactKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long?>("ByteLength")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiagnosticJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("EngineTargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ExecutionJobId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExpectedJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("FormatVersion")
                        .HasColumnType("integer");

                    b.Property<string>("ObjectKey")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ValidationRunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactKey")
                        .IsUnique();

                    b.HasIndex("EngineTargetId")
                        .IsUnique();

                    b.HasIndex("ExecutionJobId");

                    b.HasIndex("Status", "UpdatedAt");

                    b.ToTable("SqlExpectedArtifacts", null, t =>
                        {
                            t.HasCheckConstraint("CK_SqlExpectedArtifacts_Hash", "\"ContentHash\" IS NULL OR \"ContentHash\" ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("CK_SqlExpectedArtifacts_Key", "\"ArtifactKey\" ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("CK_SqlExpectedArtifacts_Size", "\"FormatVersion\" > 0 AND (\"ByteLength\" IS NULL OR \"ByteLength\" >= 0)");

                            t.HasCheckConstraint("CK_SqlExpectedArtifacts_Status", "\"Status\" IN ('pending', 'validating', 'valid', 'invalid')");

                            t.HasCheckConstraint("CK_SqlExpectedArtifacts_Storage", "NOT (\"ExpectedJson\" IS NOT NULL AND \"ObjectKey\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_SqlExpectedArtifacts_Valid", "\"Status\" <> 'valid' OR (\"ValidatedAt\" IS NOT NULL AND \"ErrorCode\" IS NULL AND \"ContentHash\" IS NOT NULL AND \"ByteLength\" IS NOT NULL AND (\"ExpectedJson\" IS NOT NULL OR \"ObjectKey\" IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("TaskForge.Tasks.Api.Domain.TaskAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswersJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<int>("CorrectUnits")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EarnedScore")
                        .HasColumnType("integer");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OrderJson")
                        .HasColumnType("jsonb");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<string>("ReviewJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("ScorePercent")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TaskAssignmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TimeExpired")
                        .HasColumnType("boolean");

                    b.Property<int?>("TimeLimitSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer");

                    b.Property<int>("TotalUnits")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskAssignmentId", "Kind", "AttemptNumber");

                    b.HasIndex("UserId", "Kind", "TaskAssignmentId", "SubmittedAt");

                    b.ToTable("TaskAttempts", (string)null);
                });

            modelBuilder.Entity("TaskForge.Tasks.Api.Domain.Sql.SqlAssignmentEngineTarget", b =>
                {
                    b.HasOne("TaskForge.Tasks.Api.Domain.Sql.SqlEngineProfile", null)
                        .WithMany()
                        .HasForeignKey("EngineProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskForge.Tasks.Api.Domain.Sql.SqlAssignmentSpecVersion", null)
                        .WithMany()
                        .HasForeignKey("SpecVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskForge.Tasks.Api.Domain.Sql.SqlAssignmentSpec", b =>
                {
                    b.HasOne("TaskForge.Tasks.Api.Domain.Assignment", null)
                        .WithOne()
                        .HasForeignKey("TaskForge.Tasks.Api.Domain.Sql.SqlAssignmentSpec", "AssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskForge.Tasks.Api.Domain.Sql.SqlAssignmentSpecVersion", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId", "DraftVersionId")
                        .HasPrincipalKey("AssignmentId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TaskForge.Tasks.Api.Domain.Sql.SqlAssignmentSpecVersion", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId", "PublishedVersionId")
                        .HasPrincipalKey("AssignmentId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TaskForge.Tasks.Api.Domain.Sql.SqlAssignmentSpecVersion", b =>
                {
                    b.HasOne("TaskForge.Tasks.Api.Domain.Sql.SqlAssignmentSpec", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskForge.Tasks.Api.Domain.Sql.SqlDatasetVersion", null)
                        .WithMany()
                        .HasForeignKey("DatasetVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskForge.Tasks.Api.Domain.Sql.SqlDatasetEngineValidation", b =>
                {
                    b.HasOne("TaskForge.Tasks.Api.Domain.Sql.SqlDatasetVersion", null)
                        .WithMany()
                        .HasForeignKey("DatasetVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskForge.Tasks.Api.Domain.Sql.SqlEngineProfile", null)
                        .WithMany()
                        .HasForeignKey("EngineProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskForge.Tasks.Api.Domain.Sql.SqlDatasetVersion", b =>
                {
                    b.HasOne("TaskForge.Tasks.Api.Domain.Sql.SqlDataset", null)
                        .WithMany()
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskForge.Tasks.Api.Domain.Sql.SqlExpectedArtifact", b =>
                {
                    b.HasOne("TaskForge.Tasks.Api.Domain.Sql.SqlAssignmentEngineTarget", null)
                        .WithOne()
                        .HasForeignKey("TaskForge.Tasks.Api.Domain.Sql.SqlExpectedArtifact", "EngineTargetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
