// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskForge.Tasks.Api.Data;

#nullable disable

namespace TaskForge.Tasks.Api.Migrations
{
    [DbContext(typeof(TasksDbContext))]
    [Migration("20260624085810_AddAssignmentAnalytics")]
    partial class AddAssignmentAnalytics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskForge.Tasks.Api.Domain.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllowedLanguagesCsv")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("AnalyticsSettingsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("CodeForbiddenCallsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("CodeRequiredCallsJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("Sort")
                        .HasColumnType("integer");

                    b.Property<string>("StarterCode")
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("TestsJson")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "Sort");

                    b.ToTable("Assignments", (string)null);
                });

            modelBuilder.Entity("TaskForge.Tasks.Api.Domain.AssignmentActivityEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("ActiveDurationMs")
                        .HasColumnType("bigint");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<long?>("BlurDurationMs")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ClientTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CodeDelta")
                        .HasColumnType("integer");

                    b.Property<string>("CodeHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("CodeLength")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("EventUid")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<long?>("HiddenDurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("IpHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Language")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("RiskPoints")
                        .HasColumnType("integer");

                    b.Property<string>("RiskReason")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid?>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TextHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("TextLength")
                        .HasColumnType("integer");

                    b.Property<string>("TextSample")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("UserAgentHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId", "CreatedAt");

                    b.HasIndex("AssignmentId", "EventType", "CreatedAt");

                    b.HasIndex("AssignmentId", "UserId", "SessionId", "CreatedAt");

                    b.HasIndex("AssignmentId", "UserId", "SessionId", "EventUid")
                        .IsUnique();

                    b.ToTable("AssignmentActivityEvents", (string)null);
                });

            modelBuilder.Entity("TaskForge.Tasks.Api.Domain.AssignmentCodeSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<int?>("CodeDelta")
                        .HasColumnType("integer");

                    b.Property<string>("CodeHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("CodeLength")
                        .HasColumnType("integer");

                    b.Property<string>("CodeSample")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullCode")
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid?>("RelatedEventId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RelatedSubmissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId", "CodeHash");

                    b.HasIndex("AssignmentId", "SessionId", "CreatedAt");

                    b.HasIndex("AssignmentId", "UserId", "CreatedAt");

                    b.ToTable("AssignmentCodeSnapshots", (string)null);
                });

            modelBuilder.Entity("TaskForge.Tasks.Api.Domain.AssignmentWorkSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ActiveDurationMs")
                        .HasColumnType("bigint");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("BlurCount")
                        .HasColumnType("integer");

                    b.Property<long>("BlurDurationMs")
                        .HasColumnType("bigint");

                    b.Property<int>("CloseCount")
                        .HasColumnType("integer");

                    b.Property<int>("CodeChangeCount")
                        .HasColumnType("integer");

                    b.Property<int>("CopyCount")
                        .HasColumnType("integer");

                    b.Property<int>("CutCount")
                        .HasColumnType("integer");

                    b.Property<int>("FailedSubmitCount")
                        .HasColumnType("integer");

                    b.Property<string>("FinalCodeHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("FinalCodeLength")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FocusCount")
                        .HasColumnType("integer");

                    b.Property<int>("FullscreenExitCount")
                        .HasColumnType("integer");

                    b.Property<int>("HiddenCount")
                        .HasColumnType("integer");

                    b.Property<long>("HiddenDurationMs")
                        .HasColumnType("bigint");

                    b.Property<int>("LanguageChangeCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastEventType")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("LastLanguage")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("MaxCodeLength")
                        .HasColumnType("integer");

                    b.Property<int>("OpenCount")
                        .HasColumnType("integer");

                    b.Property<int>("PassedSubmitCount")
                        .HasColumnType("integer");

                    b.Property<int>("PasteCount")
                        .HasColumnType("integer");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RiskReasonsJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("RiskScore")
                        .HasColumnType("integer");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SubmitCount")
                        .HasColumnType("integer");

                    b.Property<long>("TotalDurationMs")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("VisibleCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId", "LastActivityAt");

                    b.HasIndex("AssignmentId", "RiskScore");

                    b.HasIndex("AssignmentId", "UserId", "SessionId")
                        .IsUnique();

                    b.ToTable("AssignmentWorkSessions", (string)null);
                });

            modelBuilder.Entity("TaskForge.Tasks.Api.Domain.ServiceSchemaMarker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.ToTable("ServiceSchemaMarkers", (string)null);
                });

            modelBuilder.Entity("TaskForge.Tasks.Api.Domain.TaskAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswersJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<int>("CorrectUnits")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EarnedScore")
                        .HasColumnType("integer");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OrderJson")
                        .HasColumnType("jsonb");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<string>("ReviewJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("ScorePercent")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TaskAssignmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TimeExpired")
                        .HasColumnType("boolean");

                    b.Property<int?>("TimeLimitSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer");

                    b.Property<int>("TotalUnits")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskAssignmentId", "Kind", "AttemptNumber");

                    b.HasIndex("UserId", "Kind", "TaskAssignmentId", "SubmittedAt");

                    b.ToTable("TaskAttempts", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
