import React, { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { BookOpen, ChevronRight, Loader2, PencilLine, Search, Sparkles } from 'lucide-react';
import { getLearningCourseTree } from '../api/learning';
import { useEditorMode } from '../contexts/EditorModeContext';

function flatten(nodes, level = 0, result = []) { (nodes || []).forEach((n) => { result.push({ ...n, level }); flatten(n.children, level + 1, result); }); return result; }
function kind(c) { if (c?.sectionCode) return 'Раздел'; if (c?.examCode) return 'Экзамен'; if (!c?.parentCourseId) return 'Предмет'; return 'Тема'; }
function firstNode(nodes) { const f = flatten(nodes); return f.find((x) => x.examCode || x.sectionCode) || f[0] || null; }
export default function LearningHomePage() {
  const { canEdit, isEditorMode } = useEditorMode();
  const [tree, setTree] = useState([]);
  const [q, setQ] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  useEffect(() => { let off = false; (async () => { try { setLoading(true); const data = await getLearningCourseTree({ includeDraft: isEditorMode }); if (!off) setTree(data || []); } catch (e) { if (!off) setError(e?.userMessage || e?.message || 'Не удалось загрузить учебное дерево.'); } finally { if (!off) setLoading(false); } })(); return () => { off = true; }; }, [isEditorMode]);
  const visible = useMemo(() => { const s = q.trim().toLowerCase(); if (!s) return tree; const m = (c) => `${c.title || ''} ${c.shortTitle || ''} ${c.summary || ''} ${c.description || ''} ${c.sectionCode || ''}`.toLowerCase().includes(s) || (c.children || []).some(m); return tree.filter(m); }, [tree, q]);
  const editable = useMemo(() => firstNode(tree), [tree]);
  const href = (c) => (isEditorMode && c.sectionCode) ? `/${String(c.sectionCode).toLowerCase()}` : `/courses/${c.slug}`;
  return <><div className="min-h-[calc(100vh-57px)] bg-neutral-50 dark:bg-neutral-950"><div className="container-app py-6 lg:py-8">
    <section className="rounded-[2rem] border border-neutral-200/80 dark:border-neutral-800 bg-white dark:bg-neutral-900 shadow-soft p-6 md:p-8">
      <div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-brand-200 bg-brand-50 px-3 py-1 text-sm font-semibold text-brand-800 dark:border-brand-800 dark:bg-brand-900/20 dark:text-brand-100"><BookOpen size={16} />TaskForge CT</div><h1 className="text-4xl md:text-5xl font-bold tracking-tight">Учебные курсы ЦТ/ЦЭ</h1><p className="mt-4 max-w-3xl text-lg leading-8 text-neutral-600 dark:text-neutral-300">Отдельная ветка подготовки: предметы, экзамены, разделы, темы, конспекты и мини-задания. Старые программные курсы здесь не используются.</p></div><div className="rounded-3xl border border-neutral-200 dark:border-neutral-800 bg-neutral-50 dark:bg-neutral-950 p-5 lg:w-80"><div className="flex items-center gap-2 font-semibold"><Sparkles size={18} /> Логика</div><p className="mt-2 text-sm leading-6 text-neutral-600 dark:text-neutral-300">Предмет → экзамен → раздел → тема → конспекты и задания.</p>{canEdit && <Link to={editable?.sectionCode ? `/${String(editable.sectionCode).toLowerCase()}` : '/'} className="btn-outline mt-4 inline-flex items-center gap-2"><PencilLine size={16} />Открыть редактор</Link>}</div></div>
    </section>
    {isEditorMode && <div className="mt-5 rounded-3xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900 dark:border-amber-900 dark:bg-amber-950/20 dark:text-amber-100">Режим редактора включён: конкретные номера открываются той же страницей с редактором сверху.</div>}
    <section className="mt-6 rounded-[2rem] border border-neutral-200/80 dark:border-neutral-800 bg-white dark:bg-neutral-900 p-4 shadow-soft"><label className="relative block"><Search size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-neutral-400" /><input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Найти предмет, экзамен, раздел или тему" className="w-full rounded-2xl border border-neutral-200 dark:border-neutral-800 bg-neutral-50 dark:bg-neutral-950 py-3 pl-12 pr-4 text-base outline-none focus:border-brand-400" /></label></section>
    {error && <div className="mt-6 rounded-3xl border border-red-200 bg-red-50 p-4 text-sm text-red-800 dark:border-red-900 dark:bg-red-950/20 dark:text-red-100">{error}</div>}
    {loading ? <div className="mt-6 rounded-[2rem] border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 p-10 text-center shadow-soft"><Loader2 className="mx-auto animate-spin text-brand-600" /><div className="mt-3 text-neutral-600 dark:text-neutral-300">Загружаю...</div></div> : <><div className="mt-5 text-sm text-neutral-500 dark:text-neutral-400">Учебных узлов: {flatten(tree).length}</div><div className="mt-4 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{visible.map((c) => <Link key={c.id} to={href(c)} className="group rounded-[2rem] border border-neutral-200/80 dark:border-neutral-800 bg-white dark:bg-neutral-900 p-6 shadow-soft transition hover:-translate-y-0.5 hover:border-brand-300 hover:shadow-xl"><div className="mb-5 grid h-12 w-12 place-items-center rounded-2xl bg-brand-50 text-brand-700 dark:bg-brand-900/20 dark:text-brand-200">{isEditorMode ? <PencilLine size={22} /> : <BookOpen size={22} />}</div><div className="text-sm font-semibold uppercase tracking-wide text-brand-700 dark:text-brand-300">{kind(c)}</div><h2 className="mt-2 text-2xl font-bold group-hover:text-brand-700 dark:group-hover:text-brand-200">{c.title}</h2>{(c.summary || c.description) && <p className="mt-3 line-clamp-3 leading-7 text-neutral-600 dark:text-neutral-300">{c.summary || c.description}</p>}<div className="mt-5 flex items-center gap-2 font-semibold text-brand-700 dark:text-brand-200">{isEditorMode ? 'Редактировать' : 'Открыть'}<ChevronRight size={18} /></div></Link>)}</div></>}
  </div></div></>;
}
