// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskForge.Execution.Api.Data;

#nullable disable

namespace TaskForge.Execution.Api.Migrations
{
    [DbContext(typeof(ExecutionDbContext))]
    [Migration("20260909054614_AddSqlDomain")]
    partial class AddSqlDomain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskForge.Execution.Api.Domain.ExecutionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("ClaimedByWorkerId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodeForbiddenCallsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("CodeRequiredCallsJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeduplicationKey")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Input")
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasDefaultValue("legacy");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uuid");

                    b.Property<int?>("MemoryLimitMb")
                        .HasColumnType("integer");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb");

                    b.Property<int?>("PayloadVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid?>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Target")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("TestsJson")
                        .HasColumnType("text");

                    b.Property<int?>("TimeLimitMs")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeduplicationKey")
                        .IsUnique();

                    b.HasIndex("SubmissionId");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("Status", "LeaseExpiresAt");

                    b.HasIndex("Status", "Kind", "Target", "CreatedAt");

                    b.ToTable("ExecutionJobs", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExecutionJobs_Kind", "\"Kind\" IN ('legacy', 'code', 'image', 'sql-check', 'sql-preview', 'sql-materialize')");

                            t.HasCheckConstraint("CK_ExecutionJobs_Lease", "(\"ClaimedByWorkerId\" IS NULL AND \"LeaseToken\" IS NULL AND \"LeaseExpiresAt\" IS NULL) OR (\"ClaimedByWorkerId\" IS NOT NULL AND \"LeaseToken\" IS NOT NULL AND \"LeaseExpiresAt\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_ExecutionJobs_Payload", "(\"Kind\" = 'legacy' AND \"PayloadVersion\" IS NULL AND \"PayloadJson\" IS NULL) OR (\"Kind\" <> 'legacy' AND \"Target\" IS NOT NULL AND length(\"Target\") > 0 AND \"PayloadVersion\" IS NOT NULL AND \"PayloadVersion\" > 0 AND \"PayloadJson\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_ExecutionJobs_SqlNoLegacyTests", "\"Kind\" NOT IN ('sql-check', 'sql-preview', 'sql-materialize') OR (\"TestsJson\" IS NULL AND \"CodeForbiddenCallsJson\" IS NULL AND \"CodeRequiredCallsJson\" IS NULL)");

                            t.HasCheckConstraint("CK_ExecutionJobs_SqlSubmission", "(\"Kind\" NOT IN ('sql-preview', 'sql-materialize') OR \"SubmissionId\" IS NULL) AND (\"Kind\" <> 'sql-check' OR (\"SubmissionId\" IS NOT NULL AND \"AssignmentId\" IS NOT NULL AND \"UserId\" IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("TaskForge.Execution.Api.Domain.ExecutionResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("integer");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Stderr")
                        .HasColumnType("text");

                    b.Property<string>("Stdout")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.ToTable("ExecutionResults", (string)null);
                });

            modelBuilder.Entity("TaskForge.Execution.Api.Domain.RunnerHeartbeat", b =>
                {
                    b.Property<string>("RunnerId")
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("RunnerId");

                    b.ToTable("RunnerHeartbeats", (string)null);
                });

            modelBuilder.Entity("TaskForge.Execution.Api.Domain.ServiceSchemaMarker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.ToTable("ServiceSchemaMarkers", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
