// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskForge.Minecraft.Api.Data;

#nullable disable

namespace TaskForge.Minecraft.Api.Migrations
{
    [DbContext(typeof(MinecraftDbContext))]
    partial class MinecraftDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskForge.Minecraft.Api.Domain.MinecraftChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("Author");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("Text");

                    b.Property<string>("MinecraftNick")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MinecraftUuid")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("SiteUser");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_MinecraftChatMessages_CreatedAt");

                    b.ToTable("MinecraftChatMessages", (string)null);
                });

            modelBuilder.Entity("TaskForge.Minecraft.Api.Domain.MinecraftDeathRecovery", b =>
                {
                    b.Property<Guid>("DeathId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("BackendUnavailable")
                        .HasColumnType("boolean");

                    b.Property<int>("ChargedAmount")
                        .HasColumnType("integer");

                    b.Property<bool>("ChestCreated")
                        .HasColumnType("boolean");

                    b.Property<int?>("ChestSecondX")
                        .HasColumnType("integer");

                    b.Property<int?>("ChestSecondY")
                        .HasColumnType("integer");

                    b.Property<int?>("ChestSecondZ")
                        .HasColumnType("integer");

                    b.Property<bool>("ChestSpotReserved")
                        .HasColumnType("boolean");

                    b.Property<int?>("ChestX")
                        .HasColumnType("integer");

                    b.Property<int?>("ChestY")
                        .HasColumnType("integer");

                    b.Property<int?>("ChestZ")
                        .HasColumnType("integer");

                    b.Property<bool>("Compensated")
                        .HasColumnType("boolean");

                    b.Property<bool>("CompensationPending")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DropsReleased")
                        .HasColumnType("boolean");

                    b.Property<double?>("FinalX")
                        .HasColumnType("double precision");

                    b.Property<double?>("FinalY")
                        .HasColumnType("double precision");

                    b.Property<double?>("FinalZ")
                        .HasColumnType("double precision");

                    b.Property<string>("ItemsPayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ItemsResolved")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset>("OfferExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<float>("Pitch")
                        .HasColumnType("real");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("PlayerUuid")
                        .HasColumnType("uuid");

                    b.Property<string>("PreviousGameMode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PurchaseRequestId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("RescueCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("RescueEndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RescuePending")
                        .HasColumnType("boolean");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorldKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("WorldName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("WorldUuid")
                        .HasColumnType("uuid");

                    b.Property<double>("X")
                        .HasColumnType("double precision");

                    b.Property<double>("Y")
                        .HasColumnType("double precision");

                    b.Property<float>("Yaw")
                        .HasColumnType("real");

                    b.Property<double>("Z")
                        .HasColumnType("double precision");

                    b.HasKey("DeathId");

                    b.HasIndex("PurchaseRequestId")
                        .IsUnique();

                    b.HasIndex("PlayerUuid", "OfferExpiresAtUtc");

                    b.HasIndex("Stage", "UpdatedAtUtc");

                    b.ToTable("MinecraftDeathRecoveries", (string)null);
                });

            modelBuilder.Entity("TaskForge.Minecraft.Api.Domain.MinecraftLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlayerName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PlayerUuid")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset?>("UnlinkedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("UserId", "Confirmed", "UnlinkedAtUtc");

                    b.ToTable("MinecraftLinks", (string)null);
                });

            modelBuilder.Entity("TaskForge.Minecraft.Api.Domain.MinecraftLinkCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nick")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ExpiresAtUtc", "UsedAtUtc");

                    b.ToTable("MinecraftLinkCodes", (string)null);
                });

            modelBuilder.Entity("TaskForge.Minecraft.Api.Domain.MinecraftRatingTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Delta")
                        .HasColumnType("integer");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("PlayerName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PlayerUuid")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RequestId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("MinecraftRatingTransactions", (string)null);
                });

            modelBuilder.Entity("TaskForge.Minecraft.Api.Domain.ServiceSchemaMarker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.ToTable("ServiceSchemaMarkers", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
