import api from './http';
const body = promise => promise.then(response => response.data);
export const sqlEngines = () => body(api.get('/api/sql/engines'));
export const sqlRuntime = () => body(api.get('/api/execution/sql-status'));
export const sqlDatasets = () => body(api.get('/api/sql/datasets'));
export const sqlDataset = id => body(api.get(`/api/sql/datasets/${id}`));
export const sqlDatasetVersion = (id, version) => body(api.get(`/api/sql/datasets/${id}/versions/${version}`));
export const createSqlDataset = input => body(api.post('/api/sql/datasets', input));
export const updateSqlDataset = (id, input) => body(api.put(`/api/sql/datasets/${id}`, input));
export const createSqlDatasetVersion = (id, input) => body(api.post(`/api/sql/datasets/${id}/versions`, input));
